# Generated by Django 4.0.4 on 2022-05-18 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatestUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_updated_date', models.DateTimeField(default=datetime.datetime(2022, 5, 19, 3, 1, 41, 87218))),
            ],
        ),
    ]
