# Generated by Django 4.0.4 on 2022-05-19 01:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='latestupdated',
            name='id',
        ),
        migrations.AlterField(
            model_name='latestupdated',
            name='latest_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 8, 8, 30, 766560), primary_key=True, serialize=False),
        ),
    ]
