# Generated by Django 4.0.4 on 2022-05-24 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_latestupdated_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestupdated',
            name='latest_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 20, 44, 36, 363122), primary_key=True, serialize=False),
        ),
    ]
