# Generated by Django 4.0.4 on 2022-05-26 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_latestupdated_latest_updated_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestupdated',
            name='latest_updated_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 26, 11, 4, 13, 59732), primary_key=True, serialize=False),
        ),
    ]
